#!/bin/bash
mkdir -p out

docker buildx build . --platform linux/amd64 -t artifact-boolean-algebras
docker image save -o "artifact-boolean-algebras-amd64.tar" artifact-boolean-algebras

if [ -d ".git" ]; then
  echo "Git repository detected, creating zip with git history"
  git archive --format zip --output out/artifact-boolean-algebras.zip \
   --add-file artifact-boolean-algebras-amd64.tar \
   HEAD
else
  echo "No git repository detected, creating zip without git history"
  zip -r out/artifact-boolean-algebras.zip . -x "*.git*" -x "out/*"
fi
